### ISSUE TITLE
[Remove Request] -  Blocking Amazon Cognito - cognito-identity.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#101]
cognito-identity.us-east-1.amazonaws.com is a false positive
Amazon Cognito is required for some AWS apps. 
For me, it is breaking SensorPush app. 
"Amazon Cognito helps you create unique identifiers for your end users that are kept consistent across devices and platforms. Amazon Cognito lets you add user sign-up, sign-in, and access control to your web and mobile apps quickly and easily.

**Comment by mkb2091** [comment]
Thanks for reporting, it was blocked by https://raw.githubusercontent.com/blocklistproject/Lists/master/ads.txt. It's been added to the allowlist

**Comment by p1r473** [comment]
I reported it upstream but they havent actioned it yet
https://github.com/blocklistproject/Lists/issues/437
