### ISSUE TITLE
False positive: tmx.td.com

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#102]
Hi
I believe tmx.td.com is a false positive
TMX is a Canadian Finance company and TD is Toronto Dominion Bank.
Blocking this domain breaks logging into the MBNA app to manage credit cards, which is hosted by TD.

Also reported upstream, this is just a FYI.

**Comment by mkb2091** [comment]
Thanks for reporting, it was blocked by https://hostfiles.frogeye.fr/multiparty-trackers.txt and https://hblock.molinero.dev/hosts directly, and it's CNAME `h-tdcanada.online-metrix.net` was blocked by https://codeberg.org/spootle/blocklist/raw/branch/master/blocklist.txt, and https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt. I've removed the domain
