### ISSUE TITLE
inbox.google.com

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#103]
Be careful when using herrbischoff/trackers as an upstream
he is blocking Gmail
https://github.com/herrbischoff/trackers/pull/6

**Comment by herrbischoff** [comment]
This has already been resolved by https://github.com/herrbischoff/trackers/commit/d98e24c816a9f7166fd01d608ff6545b261df602. Also, @p1r473, it would be way more effective if you submitted a pull request to this project, adding `inbox.google.com` to the whitelist.

**Comment by p1r473** [comment]
@herrbischoff thanks for the quick fix.
