### ISSUE TITLE
ept.ms falsely blocked

### ISSUE THREAD

**Issue by mooleshacat** [mkb2091/blockconvert#109]
> Malware, advert and tracking blocklist which consolidates and improves upon many other blocklists

**ept.ms is part of The Epoch Times news.** This has to be a mistake that you block an entire news site?

Please let me know if this was a mistake. I only intend to block malware tracking and advertising, not block entire sites that you disagree with because of your extreme leftist political bias.

If it was a mistake, please remove it.

If this was NOT a mistake, that means you have a hard left political bias that does not belong in a blocklist that is intended for malware, advertising, and tracking and as such I will remove your lists from my pihole.

**Comment by mkb2091** [comment]
It is not currently blocked, might have been in an old version of the list
