### ISSUE TITLE
api.videos.oovvuu.com , videos.oovvuu.com 

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#16]
This domain may be a false positive. It breaks embedded videos in news articles viewed through Google News app. This article was affected on my mobile:
https://www.ndtv.com/offbeat/excited-rhino-runs-like-a-puppy-on-seeing-his-zoo-keeper-watch-2208948

**Comment by mkb2091** [comment]
They are only blocked by 1 upstream list. I checked and the video doesn't load with them blocked, so I'm whitelisting them

**Comment by p1r473** [comment]
Thanks
Do you list your upstream lists?

**Comment by mkb2091** [comment]
Yes all upstream lists are in urls.txt, it is also available in a more human readable format at https://github.com/mkb2091/blockconvert/blob/master/sources.md 

I'm only aware of 2 of them being dead, but I'll check. I've kept the dead ones so far as the program will just use the cached list from when it was active if it cannot be fetched. I probably should remove those urls from urls.txt and add their domains to blacklist.txt
