### ISSUE TITLE
Wildcards in blacklist

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#17]
Hi,
Correct me if I am wrong, but I believe blacklist.txt is supposed to be domains only
Out of 217244 domains, 5 domains are invalid due to the wildcard *
adservice.google.*
adskeeper.co.*
id.google.*
zzxosget.com*.crisp.chat
zzzmen99.had.su*.m.gxwztv.com

**Comment by mkb2091** [comment]
blacklist.txt is just a file used in the creation of the generated block lists stored at /output, so it doesn't have to be pure domains
Domains ending in ".*" are expanded to have a version with every valid domain ending (e.g. .net, .com, .org etc)
The last 2 are definitely invalid as it has the "*" in the middle of the domain, so they won't be able to be used to produce useful results

**Comment by p1r473** [comment]
Okay, thanks!
