### ISSUE TITLE
bitcoin.comnews.bitcoin.com bitcoin.cowww.bitcoin.com

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#26]
I was trying to see if you were blocking some of zerodot's other mining domains, like news.bitcoin.com and found:

bitcoin.comnews.bitcoin.com
bitcoin.cowww.bitcoin.com
Pretty sure these are accidentally concatenated
But, once you fix it, I'd really recommend not blacklistting these domains

I've opened up issues at zerodot's gitlab, but he doesn't agree with me.
I agree with blocking javascript coinminers (as they are malicious), but when he starts blocking EVERY CRYPTO NEWS WEBSITE EVER, I think he started taking it too far.

Maybe, you want to include ONLY the browser mining, and not the main list. (Main list blocks everything like coingeek and news.bitcoin.com and coinmarketcap and lots of news sites)

**Comment by mkb2091** [comment]
I wasn't aware of their being a separate list with only browser mining domains, I'll add it and remove the main list and optional list that is currently used
