### ISSUE TITLE
appleid.apple.com.akadns.net

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#28]
This is a CNAME for appleid.apple.com

**Comment by mkb2091** [comment]
I've added it to the whitelist. This could potentially be a recurring problem as appleid.apple.com was already in the whitelist, but appleid.apple.com.akadns.net was not. I'll try and figure out a solution, but until I do, I'll leave this issue open

**Comment by p1r473** [comment]
Why will it be recurring?

**Comment by mkb2091** [comment]
I mean the blocklist could contain domains that are CNAMES for whitelisted domains which would result in blocking them

**Comment by p1r473** [comment]
We will just have to keep at this then!
