### ISSUE TITLE
discord.com

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#29]
`discord.com` recently was added to the list.

Discord is a popular VoIP and chat communication service. I do not believe their webpage contains any analytical tracking for it to be placed on the list.

**Comment by p1r473** [comment]
For sure a false positive!

**Comment by mkb2091** [comment]
Yeah that is definitely a false positive. I've added it to the whitelist

**Comment by TheNoobWar** [comment]
Looks good, thank you!
