### ISSUE TITLE
soundcloud.com

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#32]
`soundcloud.com` was recently added to the list.

`soundcloud.com` appears to be a false-positive, however, the other telemetry links in the blocklist do not. By blocking `soundcloud.com` it prohibits connecting to `soundcloud.com` on Desktop, surprisingly not on the mobile apps in the same network.

**Comment by mkb2091** [comment]
Thanks for reporting. I've whitelisted soundcloud.com
