### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by bauzer714** [mkb2091/blockconvert#34]
Can you consider whitelisting the below?

*.safelinks.protection.outlook.com

https://support.microsoft.com/en-us/office/advanced-outlook-com-security-for-office-365-subscribers-882d2243-eab9-4545-a58a-b36fee4a46e2

**Comment by mkb2091** [comment]
Thanks for reporting. I wouldn't be inclined to trust it as it will redirect all links as it chooses, but since it's only for outlook users it doesn't receive any more data than it would otherwise, so I'm whitelisting it
