### ISSUE TITLE
us.archive.org

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#36]
```
ia600903.us.archive.org
ia600905.us.archive.org
ia601400.us.archive.org
ia601403.us.archive.org
ia601506.us.archive.org
ia800905.us.archive.org
ia801400.us.archive.org
ia801402.us.archive.org
ia801405.us.archive.org
ia801407.us.archive.org
ia801502.us.archive.org
ia801503.us.archive.org
ia801505.us.archive.org
ia801506.us.archive.org
ia801507.us.archive.org
ia801509.us.archive.org
```

The following are on the blocklist. These specific domains provide CDN delivery for downloads on the Internet Wayback Machine (archive.org) files. I believe they are also a false-positive.

**Comment by mkb2091** [comment]
They are all false positives caused by https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt
I am removing that list since its caused quite a few false positives
