### ISSUE TITLE
https://www.vivo.com.br/para-voce/por-que-vivo/qualidade/teste-de-velocidade#testar-velocidade false positive

### ISSUE THREAD

**Issue by SHJordan** [mkb2091/blockconvert#38]
Over-blocking. should almost had no ads... only a dns one i guess... still the website is meant test connection speed for ISP VIVO TELEFONICA.
![image](https://user-images.githubusercontent.com/884602/85098094-f2519180-b1cf-11ea-8ed2-c94aa63f47b6.png)

Disabling blockconvert adguard rules fixed it.

**Comment by mkb2091** [comment]
That is caused by vivo.com.br being in https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt
I am removing the list since it has caused quite a few false positives
