### ISSUE TITLE
IPv6 in IPv4

### ISSUE THREAD

**Issue by Cade66** [mkb2091/blockconvert#39]
Hi,

`https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/ip_blocklist.txt`
ends with `fe80::ff:fe9c:89c5` and no EOL

Thanks

**Comment by mkb2091** [comment]
Previously it supported both IPv4 and IPv6, and stored them in one file. I've removed support for IPv6 since there was only one IPv6 ip address. I've also added EOL to the last line of all of the generated files.

**Comment by Cade66** [comment]
Thanks- Will use the ip_blocklist.txt as soon as fixed.

**Comment by mkb2091** [comment]
It should now be fixed

**Comment by Cade66** [comment]
Fixed and added back to my IP blocklists.
I appreciate, thanks :=)
