### ISSUE TITLE
mvaali1.ws.byteoversea.net is a CNAME for frontier-va.tiktokv.com (TikTok social media app)

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#42]
mvaali1.ws.byteoversea.net is a CNAME for frontier-va.tiktokv.com (TikTok social media app)
This is a non malicious domain
Thanks!

**Comment by mkb2091** [comment]
Thanks for reporting it, I've added it to the whitelist (https://github.com/mkb2091/blockconvert/commit/647fb4a2b774a75f4cb996f7443b15f2f66e8115, I forgot to include the issue number in the commit)
