### ISSUE TITLE
vanilla.futurecdn.net

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#44]
This breaks the embedded YouTube videos at sites such as
https://www.pcgamer.com/five-new-steam-games-you-probably-missed-june-29-2020/

I'd recommend being careful blocking CDNs, as a Content Delivery Networks just serves static info for many clients.

**Comment by mkb2091** [comment]
Thanks, I've whitelisted it vanilla.futurecdn.net  and api.vanilla.futurecdn.net, as I'm assuming they both might break content
