### ISSUE TITLE
Whitelist Request - 	substrate.office.com

### ISSUE THREAD

**Issue by bauzer714** [mkb2091/blockconvert#45]
Microsoft To Do sync is broken if the domain is blocked.  Initializing a sync command request results in only this domain being queried. No other domain is utilized after substrate.office.com is whitelisted (such as a tracker being blocked causing a subsequent failure).

I do not have sufficient knowledge if the domain is also utilized for data tracking from other MS based applications.

**Comment by mkb2091** [comment]
Only one list blocks it (WindowsSpyBlocker extra), so I think it is a most likely a false positive. I've added it to the whitelist which means the script used to generate the blocklists will remove substrate.office.com from the list in the next version, which should be in under a day
