### ISSUE TITLE
Whitelist LinkedIn

### ISSUE THREAD

**Issue by bauzer714** [mkb2091/blockconvert#48]
LI seems like a false positive

www.linkedin.com

**Comment by mkb2091** [comment]
That is a major false positive, thanks for reporting. This has highlighted an issue in the program used to generate the blocklist, as it is saying none of the included lists are blocking that domain, while the domain is still in the generated blocklist.

**Comment by mkb2091** [comment]
Turns out one of it's old cnames (2-01-2c3e-005a.cdx.cedexis.net) was blocked which resulted in www.linkedin.com being blocked. I've whitelisted www.linkedin.com
