### ISSUE TITLE
tradingview.com

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#49]
Hello!

Found more recent false-positives in the list. This domain has quite a few subdomains listed, not all of them should be whitelisted, as most of the `tradingview.com` entries belong on the list.

These domains should be whitelisted as they provide market graphs for stocks:
`widgetdata.tradingview.com`
`s.tradingview.com`
`s3.tradingview.com`

You can see this for example on [Investopedia.com](https://www.investopedia.com/markets/quote?tvwidgetsymbol=aapl)

Cheers

**Comment by mkb2091** [comment]
Thanks for reporting, I've added it to the allowlist, and I've reported it upstream to  blocklistproject/Lists
