### ISSUE TITLE
sfdataservice.microsoft.com

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#53]
Hi again,

Found a new false-positive. The domain is `sfdataservice.microsoft.com`. Blocking this domain forbids payments made through the Microsoft store on Desktop browser usage. You can see this occur when attempting a purchase on a webpage like the [Xbox Game Pass](https://www.xbox.com/xbox-game-pass).

Thank you!

**Comment by mkb2091** [comment]
Thanks for reporting, I've removed that domain.
