### ISSUE TITLE
firebaseremoteconfig.googleapis.com 

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#54]
Hi,

The following domain is a false-positive, `firebaseremoteconfig.googleapis.com`. The purpose of this domain is to modify mobile applications without an update to the app through the Store. By having this API blocked, it may prevent an app from initial loading as it continuously calls to the domain for any possible update.

Thank you

**Comment by mkb2091** [comment]
Thanks for reporting. I've added it to the allowlist
