### ISSUE TITLE
a.espncdn.com

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#58]
This is the ESPN CDN (Entertainment and Sports Programming Network Content Delivery Network)
Blocking this breaks ESPN
ex.  https://www.espn.com/nba/story/_/id/29747523/three-game-5s-set-wednesday-postponed-bucks-decision-boycott
Reported here too https://github.com/pirat28/IHateTracker/issues/10

**Comment by mkb2091** [comment]
Thanks for reporting it upstream. I've removed the domain
