### ISSUE TITLE
A few political websites is blocked by this filter.

### ISSUE THREAD

**Issue by nolsen42** [mkb2091/blockconvert#6]
I noticed that infowars.com, infowarsstore.com, and drudgereport.com is blacklisted, false positive?

**Comment by mkb2091** [comment]
Thanks for reporting them, you are correct they are false positives. I'll remove them in the next update of the list.

**Comment by mkb2091** [comment]
I've found wsj.com and guce.huffpost.com(required for first visit of huffpost.com) are also blocked, and will be removed
