### ISSUE TITLE
manager-magazin-de.manager-magazin.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [mkb2091/blockconvert#60]
The site `manager-magazin-de.manager-magazin.de` is blocked by this blocklist but the site is needed to accept the cookie banner on `https://www.manager-magazin.de`. 

The cookie banner is server side so its not possible to block the cookie banner with a Adblocker or go around it.

**Comment by mkb2091** [comment]
Thanks for reporting. I've removed the domain
