### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by e-ct** [mkb2091/blockconvert#62]
Hi,
@mkb2091 

Regarding the whitelist, can you please make some adjustments?

1.Add a title (Easy to grab)
2.Can the copy be converted to ABP format?
3.Please add this to the whitelist.

`s.yimg.com`

Thank you!

**Comment by mkb2091** [comment]
I used to include an ABP version, but wasn't aware of anyone using so I removed it. I'll create the file with the appropriate title/headings. As for `s.yimg.com`, what does it break that requires it being whitelisted?

**Comment by e-ct** [comment]
Ok, please omit that one directly.

**Comment by mkb2091** [comment]
I've created an ABP style whitelist: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/whitelist_adblock.txt, turns out s.yimg.com is already in the whitelist

**Comment by e-ct** [comment]
@mkb2091 
`s.yimg.com`
It is because yahoo has special bindings in some areas, which will cause some content to be displayed incorrectly before it needs to be whitelisted.
thank you!
