### ISSUE TITLE
NSFW Site

### ISSUE THREAD

**Issue by edinjapan** [mkb2091/blockconvert#65]
Regarding si6ling.incestflix.com 
This NSFW domain hosts static assets for its main NSFW domain. It does not host any ads or any malware.
I have reported this on a few lists, so if this is just an upstream problem feel free to ignore this issue.

**Comment by mkb2091** [comment]
The upstream list that blocks it is https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt, is that one of those lists?

**Comment by edinjapan** [comment]
Yea https://github.com/jerryn70/GoodbyeAds/issues/122

**Comment by mkb2091** [comment]
I've removed the domain, and thanks for reporting
