### ISSUE TITLE
manifest.prod.boltdns.net

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#66]
This domain is the manifest for boltDNS. Blocking this domain breaks embedded videos that use the BrightCove player. It is also a CNAME for dualstack.brightcove.map.fastly.net
 For example, try and play the embedded video on https://www.intel.ca/content/www/ca/en/products/docs/processors/core/performance-maximizer.html
This domain does not host any ads, spyware, or malware.
Reported upstream https://github.com/EnergizedProtection/block/issues/557

**Comment by mkb2091** [comment]
Thanks for reporting, I've removed the domain
