### ISSUE TITLE
wd-prod-ss.trafficmanager.net

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#68]
Hello again,

`wd-prod-ss.trafficmanager.net` a CNAME for `checkappexec.microsoft.com` is a false-positive.

`checkappexec.microsoft.com` is part of Windows Defender SmartScreen to checking a file executable if it is malicious.

Thank you!

**Comment by mkb2091** [comment]
Thanks for reporting, I've added it to the allowlist
