### ISSUE TITLE
wildcard in *.getemails.com

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#69]
Hello
I am not sure if you are supporting wildcards on purpose
But if it snuck there on accident, I am reporting a possible invalid domain

*.getemails.com

If you meant to include wildcards in this list you can ignore this issue
Thanks

**Comment by mkb2091** [comment]
Yes, it is intended that files in internal (such as https://raw.githubusercontent.com/mkb2091/blockconvert/master/internal/blocklist.txt which I believe is the only file with that wildcard) may contain wildcards. Files in output folder (such as https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt) should not contain any wildcards
