### ISSUE TITLE
Whitelist sendgrid.com

### ISSUE THREAD

**Issue by bauzer714** [mkb2091/blockconvert#70]
Requesting whitelist on below domain 

> sendgrid.com

I've not actually seen sendgrid.com used for any tracking. Typically the tracking urls are similar to the below. They do have valid subdomains that shouldn't be blocked.

Tracking (Possibly more sub domains are used for tracking)
> (random alphanum).ct.sendgrid.net

Valid 
> smtp.sendgrid.net

**Comment by mkb2091** [comment]
The subdomains you mentioned are for sendgrid.net. Are you requesting both sendgrid.com and sendgrid.net should be whitelisted?

**Comment by bauzer714** [comment]
Only .com, the rest of the post is from my analysis and research to help you evaluate the request.

**Comment by mkb2091** [comment]
Ok. Thanks for reporting, and thanks for also finding a pattern for tracking domains. I'll remove sendgrid.com
