### ISSUE TITLE
matterport.com

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#72]
Hi there,

Found a couple of new false positives.

`static.matterport.com`
`my.matterport.com`

These domains are used for a 3D space capture platform. With these domains blocked, it will not display the webpage.

Thank you!

**Comment by mkb2091** [comment]
Thanks for reporting them. They were both blocked by https://raw.githubusercontent.com/blocklistproject/Lists/master/ads.txt. I've removed both of the domains
