### ISSUE TITLE
False positive: www.theepochtimes.com theepochtimes.com 

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#73]
Hi, I believe this to be a false positive
This is a online newspaper
This domain is not malware or spyware

Also reported: https://github.com/EnergizedProtection/block/issues/602

**Comment by mkb2091** [comment]
Thanks for reporting it upstream (https://github.com/jackrabbit335/UsefulLinuxShellScripts/issues/1). I've removed those domains
