### ISSUE TITLE
Whitelist stats.foldingathome.org

### ISSUE THREAD

**Issue by bauzer714** [mkb2091/blockconvert#74]
Whitelist stats.foldingathome.org. I'm not sure why this would be blocked.

**Comment by mkb2091** [comment]
Thanks for reporting. It was blocked by https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list. I've whitelisted the domain

**Comment by mkb2091** [comment]
Thanks for reporting. It was blocked by https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list. I've whitelisted the domain
