### ISSUE TITLE
ip107307705.ahcdn.com XXX streaming site

### ISSUE THREAD

**Issue by edinjapan** [mkb2091/blockconvert#75]
This domain serves videos on shemalez.com streaming XXX site
Reported upstream https://github.com/EnergizedProtection/block/issues/641

**Comment by mkb2091** [comment]
Thanks for reporting it. I've removed that domain

**Comment by edinjapan** [comment]
can you do ip107316446.ahcdn.com too?
Thanks

**Comment by mkb2091** [comment]
Thanks for reporting, and reporting it upstream to https://github.com/jerryn70/GoodbyeAds/issues/161. It'll be removed in the next commit
