### ISSUE TITLE
False positive found

### ISSUE THREAD

**Issue by nolsen42** [mkb2091/blockconvert#8]
blog.gab.com
btcpay.gab.com
business.gab.com
code.gab.com
develop.gab.com
develop.pro.gab.com
docker.develop.gab.com
eng-001.develop.gab.com
eng-002.develop.gab.com
gab.com
help.gab.com
invest.gab.com
mailer.gab.com
news.gab.com
not-develop.gab.com
ns1.gab.com
pro.gab.com
share.gab.com
shop.gab.com
trends.gab.com
unsubscribe.gab.com
www.blog.gab.com
www.gab.com
www.news.gab.com

These are safe domains, not sure why would they be blocked.

**Comment by mkb2091** [comment]
Thanks for reporting, I'll have a look in about 9 hours when I get home. I imagine a blocklist has *.gab.com for some reason which got expanded, but I'll check why and whitelist
