### ISSUE TITLE
alcohol-soft.com 

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#80]
Software vendor that makes CD Burning software Alcohol 120%
Reported upstream https://github.com/EnergizedProtection/block/issues/650
serial.alcohol-soft.com 
trial.alcohol-soft.com

**Comment by mkb2091** [comment]
Thanks for reporting. They are both blocked by https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt, thanks for reporting it upstream
