### ISSUE TITLE
secure.indeed.com

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#84]
Hi there,

The following domain `secure.indeed.com` is a false-positive.

The domain is used for user account login on an employment website. The domain being blocked prevents the webpage from displaying to login.

Thank you!

**Comment by mkb2091** [comment]
Thanks for  reporting. That was blocked by https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt, and https://hblock.molinero.dev/hosts. I've removed that domain
