### ISSUE TITLE
bgp.he.net

### ISSUE THREAD

**Issue by TheNoobWar** [mkb2091/blockconvert#86]
Hello,

I have found a false-positive. `bgp.he.net` is part of [Hurricane Electric](https://en.wikipedia.org/wiki/Hurricane_Electric)'s Internet Toolkit. 

Thank you!

**Comment by mkb2091** [comment]
Thanks again for reporting. That domain was blocked by  https://raw.githubusercontent.com/ligyxy/Blocklist/master/BLOCKLIST which judged it as being a low quality site, and clearly it isn't, so I've removed the domain
