### ISSUE TITLE
Invalid domains (illegal characters)

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#9]
*.ecology-tech403.ml
*.sublimerevenue.com

**Comment by mkb2091** [comment]
Those are only in the blacklist.txt file. blacklist.txt contains domains that have been manually added or domains from non-updated blocklists. It is used to as part of generating the blacklist, and is not the file that contains the generated blacklist.

The file that contains the generated blocklist is output/domains.txt. Sorry for not making it clear.

**Comment by p1r473** [comment]
Ok. I am using the file in my PiHole and it alerted me those domains are invalid. In case you want to remove them. Up to you.
