### ISSUE TITLE
Update lists via scheduled task

### ISSUE THREAD

**Issue by reconman** [mkb2091/blockconvert#95]
I looked a bit into your commits and it seems that you're doing updates every few days sporadically and you're not using your own update script, at least the commit messages don't match.

I would suggest implementing the update via Github Actions, I'm using a weekly job here: https://github.com/Anime-Lists/anime-lists/blob/master/.github/workflows/update-anime-lists.yml

Because I specified `workflow_dispatch`, the Github Workflow can also be triggered manually any time I want.

**Comment by mkb2091** [comment]
Yeah I've not been using the script as the resource usage of it exceeded the capabilities of the raspberry pi I'd been using for it, so now I just run it on my Windows desktop. I don't know anything about any Windows equivalent of cron, so have just been running manually, which does mean less consistency. Do you know what the resource restrictions on github actions are? I'd particularly be concerned about RAM and network usage, as my script uses a lot of both

**Comment by reconman** [comment]
Here are the specs, I think: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

The equivalent of cron jobs in Windows are scheduled tasks: https://www.technipages.com/scheduled-task-windows

**Comment by mkb2091** [comment]
Thanks, I've created scheduled tasks as it can sometimes be useful having access to the intermediate files produces by it. So now hopefully it'll be consistent
