### ISSUE TITLE
www.eltelnetworks.com

### ISSUE THREAD

**Issue by sevkar** [mkb2091/blockconvert#97]
Why this is in blocklist?

**Comment by mkb2091** [comment]
It is blocked because https://easylist.to/easylist/easyprivacy.txt blocks one of its CNAMES (www.eltelnetworks.com.dxcloud.episerver.net) due to the rule "||episerver.net^$third-party". Do you think that this domain is a false positive?

**Comment by mkb2091** [comment]
due to the rule "||episerver.net^$third-party" causing another false positive, it has been removed so this domain is no longer in the blocklist
